### ISSUE TITLE
Failed to get plugin description

### ISSUE THREAD

**Issue by KottV** [igorski/homecorrupter#2]
Hi,

I've got this error when loading homecorropter on Linux.
Is there any additional information which I can provide?

**Comment by igorski** [comment]
Hi Konstantin, what Linux distribution are you using and what VST SDK have you used to build the plugin ? Also, what DAW / environment were you loading the plugin in ?

**Comment by KottV** [comment]
openSUSE Tumbleweed
VST3 SDK was latest on that moment.
Tested in the Carla host.

I'll try to reproduce it. IIRC it won't build with recent VST3 SDK due some changes in their namespaces.

**Comment by fractalf** [comment]
@KottV Hi, I build this today in an ubuntu container.. should work on any amd64 linux systems...

https://github.com/igorski/homecorrupter/issues/5#issuecomment-1409233466

**Comment by KottV** [comment]
@fractalf 
Hi!

Still the same, testing with Carla 2.5.2:
```
carla-single vst3 ~/.vst3/homecorrupter.vst3
['/usr/lib64/carla/carla-bridge-native', 'vst3', '/home/kv/.vst3/homecorrupter.vst3', '(none)', '0']
libjack.so.0 loaded successfully!
JUCE Assertion failure in juce_VST3PluginFormat.cpp:999
JUCE Assertion failure in juce_VST3PluginFormat.cpp:3802
[carla] Plugin failed to load, error was:
Failed to get plugin description
```

**Comment by KottV** [comment]
Well, Carla uses JUCE VST3 Host code. Might be there is a problem, with Steinberg SDK's editorhost the plugin loads fine.

**Comment by igorski** [comment]
Taking the latest state of the repository (pay attention to the newly added `setup.sh` script for local installation and setup of the Steinberg SDK), is this still the issue?

**Comment by KottV** [comment]
Oh, this problem is not present anymore with v1.1.3  and VSD3 SDK 3.7.10_build_14
Sorry, I completely forgot to close this issue!
